project_id = "gielqkfnsypadbplaaci"

[functions.setup-admin]
verify_jwt = false

[functions.add-admin]
verify_jwt = false

[functions.bulk-add-products]
verify_jwt = false

[functions.update-product-images]
verify_jwt = false