// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwlonviycrvejqbhlyaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3bG9udml5Y3J2ZWpxYmhseWFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA1NDg0MjQsImV4cCI6MjA5NjEyNDQyNH0.GveVu8CuhjPYz5ACqGmYDrAp3ny420DDBa1tuVChgPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});