// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gielqkfnsypadbplaaci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpZWxxa2Zuc3lwYWRicGxhYWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzMyMDQsImV4cCI6MjA3Mzg0OTIwNH0.1jnDkMq-HCCHp2HDWag1Qwn5VR7uo-yUHsHmj-3B8dY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});